
init:

  variables:
    SP6_LOG_NO_TIMESTAMPS: 1
    
main:
  build:
    pre: |
      set -e
      export SP6_DUMP_TASK_CODE=1
      zef update 
      zef upgrade Tomty --/test
      zef install . --/test
      tomty  --all --verbose --color 
